### ISSUE TITLE
用户名或密码错误

### ISSUE THREAD

**Issue by nobisside** [yunigongshang/Schedule_jxyy#1]
你好，我在运行的时候弹出了登录窗口，但是显示是“用户名或密码错误”，程序就报错了，请问需要怎么解决

**Comment by yunigongshang** [comment]
> 你好，我在运行的时候弹出了登录窗口，但是显示是“用户名或密码错误”，程序就报错了，请问需要怎么解决

可能就是你账号错了，一般的默认密码都是xs123456

**Comment by nobisside** [comment]
好吧，我知道了，谢谢你
